# Makefile

CXX = g++
CXXFLAGS = -std=c++11 -Wall

TARGET = main
SRC = main.cpp
HEADERS = vec3.h

all: $(TARGET)

$(TARGET): $(SRC) $(HEADERS)
	$(CXX) $(CXXFLAGS) $(SRC) -o $(TARGET)

clean:
	rm -f $(TARGET)
